### PR TITLE
fix graph alignment

### LINKED ISSUE #205: [PE-D] Graph looking weird
Graph not align

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: ShawnTanzc/ped#11

### PR DESCRIPTION
**Pull request by 1-Karthigeyan-1**
Refactored further too.
fix #205

### CODE REVIEW

File: src/main/java/seedu/duke/model/GraphDrawing.java [hunk 1]
```diff
@@ -78,26 +79,25 @@ public String generateDateLabels(int maxCalorieSize,  ArrayList<LocalDate> keys)
...
+            label = this.targetCaloriesString
+                    + repeatCharacter(" ", maxSize - this.targetCaloriesString.length());
         } else if (columnNumber == 0) {
-            label = minCaloriesString
-                    + repeatCharacter(" ", calculateSizeDifference(maxCaloriesString, minCaloriesString));
+            label = this.minCaloriesString
+                    + repeatCharacter(" ", maxSize - this.minCaloriesString.length());
         } else {
-            label = space;
+            label = repeatCharacter(" ", maxSize);
```
Comment (siewwencode) [inline src/main/java/seedu/duke/model/GraphDrawing.java]: can consider making " " final

File: src/main/java/seedu/duke/model/GraphDrawing.java [hunk 2]
```diff
@@ -135,48 +135,62 @@ public String addWidth(int number) {
...
-                    drawing += TOP_BAR_WIDTH;
-                    break;
-                default:
-                    //does nothing
-                    break;
-                }
-                drawing += addWidth(i);
+
+        for (int i = GraphProperty.COLUMN - 1; i >= 0; i--) {
+            drawing += generateVerticalAxisLabel(i, GraphProperty.COLUMN, maxSize) + "|";
```
Comment (siewwencode) [inline src/main/java/seedu/duke/model/GraphDrawing.java]: can consider making "|" final

**Review by siewwencode — APPROVED** [review]
looks good!
